name: Weekly Updater

on:
  schedule:
    # Runs at 00:00 UTC on Monday every week
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run updater script
        run: python updater.py
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Weekly update
          title: Weekly Update
          body: |
            This is an automated pull request created by the weekly updater action.
            
            Changes made by running `python updater.py`
          branch: weekly-update
          base: main